--ui设置
local cjson = ts.json
w,h = getScreenSize();
MyTable = {
    ["style"]  = "default",
    ["width"] = w,          
    ["height"] = h,            
    ["cancelname"] = "取消",  
    ["okname"] = "同意条款并运行", 
    ["title"] = "INS注册脚本",  --标题栏文字
    ["titlealign"] = "left",  --title 对齐方式，默认左对齐
    ["align"] = "center", 
    ["titlesize"] = 15,  
    ["titles"] = "参数设置,其他设置,免责声明", 
    ["pagetype"]= "multi",   --多页模式
    ["selpage"] = 1,    --多页模式下指定默认停留的页面
    ["orient"] = 0,  --指定 UI 界面显示方向
    ["btnbkcolor"] = "255,255,255",         
    ["bgcolor"] = "255,255,255",
    ["pagenumtype"] = "tab", --页码样式，dot - 小圆点， number - 数字， default - 不显示，tab - 底部不显示页码样式，
    ["config"] = "peizhi.txt",  
    --["timer"] = 120,  
    ["rettype"] = "table",
    ["bg"] = "bg.png",
    pages       =
    {
        { 
            {
                ["type"] = "Label",
                ["align"] = "center",
                ["text"] = "脚本功能:",
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "ComboBox",            
                ["id"] = "脚本功能",                      
                ["list"] = "注册--APP,注册--谷歌浏览器,注册--火狐浏览器,注册--safari浏览器,登录--APP,----更多可定制功能----",   
                ["select"] = "2",                  	 -- 选填，0，默认选中项 id
                -- ["images"] = "ins.png,ins2.png,ins3.png", 
                ["scale"] = 0.15,                    -- 选填，1，图片缩放比例
                ["width"] = 500,
                ["countperline"] = 0,			
            },
            {
                ["type"] = "Label",
                ["align"] = "center",
                ["text"] = "系统版本:",
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "RadioGroup",            
                ["id"] = "系统版本",                      
                ["list"] = "IOS-12,其他版本",      -- 必填，无，多选组合内容
                ["select"] = "1",                   -- 选填，0，默认选中项 id
                ["scale"] = 0.4,                    -- 选填，1，图片缩放比例
                ["countperline"] = 0,
            },
            {
                ["type"] = "Label",
                ["align"] = "center",
                ["text"] = "注册类型:",
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "ComboBox",            
                ["id"] = "注册类型",                      
                ["list"] = "翠球邮箱,手机号接码",      -- 必填，无，多选组合内容
                ["select"] = "1",                   -- 选填，0，默认选中项 id
                 ["width"] = 500
            },
            {
                ["type"] = "Label",
                ["align"] = "center",
                ["text"] = "使用软件:",
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "top", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "ComboBox",               
                ["id"] = "使用软件",                  
                ["list"] = "AXJ,PYAPP",
                ["select"] = 1,
                ["color"] = "0,0,0",
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            }, 
            {
                ["type"] = "Label",
                ["align"] = "center",
                ["text"] = "号码地区:",
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "top", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "ComboBox",               
                ["id"] = "号码地区",                  
                ["list"] = "印尼+62,俄罗斯+7,美国+1,柬埔寨+855",
                ["select"] = 0,
                ["color"] = "0,0,0",
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            }, 
            -- {
            --     ["type"] = "Label",
            --     ["align"] = "center",
            --     ["text"] = "上传头像:",
            --     ["size"] = 15, 
            --     ["align"] = "left",          
            --     ["valign"] = "center", 
            --     ["color"] = "0,0,0",           
            --     ["width"] = -1,
            --     ["nowrap"] = 1,
            -- },
            -- {
            --     ["type"] = "Switch",
            --     ["id"] = "上传头像",
            --     ["size"] = "m",
            --     ["align"] = "left",
            --     ["valign"] = "top",
            --     ["state"] = "off",
            --     ["width"] = -1,
            --     ["nowrap"] = 1,
            -- },
            {
                ["type"] = "Label",
                ["align"] = "center",
                ["text"] = "卸载重装:",
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Switch",
                ["id"] = "卸载安装",
                ["size"] = "m",
                ["align"] = "left",
                ["valign"] = "top",
                ["state"] = "off",
                ["width"] = -1,
                ["nowrap"] = 1,
            },        
            {
                ["type"] = "Label",
                ["align"] = "center",
                ["text"] = "手动获取代理:",
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Switch",
                ["id"] = "手动获取代理",
                ["size"] = "m",
                ["align"] = "left",
                ["valign"] = "top",
                ["state"] = "off",
                ["width"] = -1,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "代理链接:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "代理链接",                  
                ["prompt"] = "你的代理链接", 
                ["kbtype"] = "default",  
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
                    {
                ["type"] = "Label", 
                ["text"] = "登录文件:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "登录文件路径",  
                ["text"] = "/private/var/mobile/Media/ces.txt",
                -- ["prompt"] = "你的账号文件路径", 
                ["kbtype"] = "default",  
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },

            -- {
            --     ["type"] = "Label", 
            --     ["text"] = "start_time:",        
            --     ["size"] = 15, 
            --     ["align"] = "left",          
            --     ["valign"] = "center", 
            --     ["color"] = "0,0,0",           
            --     ["width"] = -1,
            --     ["nowrap"] = 1,--下个控件不换行
            -- },
            -- {
            --     ["type"] = "Edit",               
            --     ["id"] = "start_time",                 
            --     --["prompt"] = "2000", 
            --     ["text"] = "2022-05-20",
            --     ["kbtype"] = "number",  
            --     ["color"] = "0,0,0",   
            --     ["size"] = 15, 
            --     ["align"] = "",           
            --     ["valign"] = "top",   
            --     ["width"] = 480,
            --     ["nowrap"] = 0,
            -- },
            -- {
            --     ["type"] = "Label", 
            --     ["text"] = "end_time:",        
            --     ["size"] = 15, 
            --     ["align"] = "left",          
            --     ["valign"] = "center", 
            --     ["color"] = "0,0,0",           
            --     ["width"] = -1,
            --     ["nowrap"] = 1,--下个控件不换行
            -- },
            -- {
            --     ["type"] = "Edit",               
            --     ["id"] = "end_time",                 
            --     --["prompt"] = "2000", 
            --     ["text"] = "2022-05-21",
            --     ["kbtype"] = "number",  
            --     ["color"] = "0,0,0",   
            --     ["size"] = 15, 
            --     ["align"] = "",           
            --     ["valign"] = "top",   
            --     ["width"] = 480,
            --     ["nowrap"] = 0,
            -- },
            {
                ["type"] = "Label", 
                ["text"] = "注册数量:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "注册数量",                 
                ["text"] = "2000",
                ["kbtype"] = "number",  
                ["color"] = "0,0,0",   
                ["size"] = 15, 
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 150,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Label", 
                ["text"] = "注册间隔:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "注册间隔",                 
                ["text"] = "120",
                ["kbtype"] = "number",  
                ["color"] = "0,0,0",   
                ["size"] = 15, 
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 170,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "防卡秒数:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "防卡时间",                  
                ["text"] = "300",
                ["kbtype"] = "number",
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 150,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Label", 
                ["text"] = "注册接口:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "ComboBox",               
                ["id"] = "接口序",                  
                ["list"] = "地址1,地址2,地址3,地址4",
                ["color"] = "0,0,0",
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 170,
                ["nowrap"] = 0,
            }, 
            {
                ["type"] = "Label", 
                ["text"] = "指定密码:",        
                ["size"] = 15, 
                ["align"] = "left", 
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Edit",               
                ["id"] = "指定密码",
                ["prompt"] = "设置指定密码/不填默认随机密码", 
                ["kbtype"] = "default", 
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "地  址  1  :",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Edit",               
                ["id"] = "电话号接口",
                ["prompt"] = "http://20.122.103.3:11223/api/v2/phone/getPhone?token=", 
                ["kbtype"] = "default", 
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "地  址  2  :",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Edit",               
                ["id"] = "电话号接口2",
                ["prompt"] = "https://api.sms-activate.org/stubs/handler_api.php?api_key=", 
                ["kbtype"] = "default", 
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "地  址  3  :",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Edit",               
                ["id"] = "电话号接口3",
                ["prompt"] = "http://20.122.103.3:11223/api/v1/sms/getPhone?token=$token&itemId=$id", 
                ["kbtype"] = "default", 
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "地  址  4  :",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,
            },
            {
                ["type"] = "Edit",               
                ["id"] = "电话号接口4",
                ["prompt"] = "http://api1.5sim.net/stubs/handler_api.php?api_key=&api_key&action=getNumber&service=lf&country=0", 
                ["kbtype"] = "default", 
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
        
        ----翠球邮箱参数-----
        {
                ["type"] = "Label", 
                ["text"] = "邮箱前缀:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "邮箱前缀",                 
                --["prompt"] = "2000", 
                ["text"] = "admin",
                --["kbtype"] = "number",  
                ["color"] = "0,0,0",   
                ["size"] = 15, 
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 150,
                ["nowrap"] = 1,
            },
        {
                ["type"] = "Label", 
                ["text"] = "邮箱后缀:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "邮箱后缀",                 
                ["prompt"] = "****.com", 
                --["text"] = "5jdj.com",
                --["kbtype"] = "number",  
                ["color"] = "0,0,0",   
                ["size"] = 15, 
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 170,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "脆球密钥:",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "脆球密钥",                 
                ["prompt"] = "b334398*********************1ba4ad7d", 
                --["text"] = "b334398cd5ca459f8c7f0d1c1ba4ad7d",
                ["kbtype"] = "default",  
                ["color"] = "0,0,0",   
                ["size"] = 15, 
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "mail_id    :",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "mail_id",                 
                ["prompt"] = "eRv****RWZ", 
                --["text"] = "eRv0R9eRWZ",
                ["kbtype"] = "default",  
                ["color"] = "0,0,0",   
                ["size"] = 15, 
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "domain_id:",        
                ["size"] = 15, 
                ["align"] = "left", 
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,     --下个控件不换行
            },
            {
                ["type"] = "Edit",               
                ["id"] = "domain_id",                 
                ["prompt"] = "RG******Dz", 
                --["text"] = "RG5YbepWDz",
                ["kbtype"] = "default",  
                ["color"] = "0,0,0",   
                ["size"] = 15, 
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 480,
                ["nowrap"] = 0,
            },        
            {
                ["type"] = "Label", 
                ["text"] = "说明：\n 1、适配6s/7/8 系统13及以上 \n 2、chrome浏览器待更新适配，仅支持火狐浏览器 \n 3、若是邮箱注册，请保证当前时区是美区【洛杉矶】时间 \n 4、【卸载重装功能】请确保【/private/var/mobile/Media/TouchSprite/res】目录下存放了【Firefox.ipa】文件",
                ["size"] = 12, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "255,140,0",           
                --["width"] = -1,
                ["nowrap"] = 0,
            }
        },
        {
            {
                ["type"] = "Label", 
                ["text"] = "用户名自定义",        
                ["size"] = 18, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 0,--下个控件换行
            },				
            {
                ["type"] = "Label", 
                ["text"] = "文件路径：",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },			
            {
                ["type"] = "Edit",               
                ["id"] = "文件路径", 
                ["text"] = "/var/mobile/Media/", 
                ["prompt"] = "/var/mobile/Media/", 
                ["kbtype"] = "default",  
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "默认路径/var/mobile/Media/",        
                ["size"] = 12, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "220,20,60",           
                ["width"] = -1,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "文件名称：",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },			
            {
                ["type"] = "Edit",               
                ["id"] = "文件名称",                  
                ["prompt"] = "用户名.txt", 
                ["kbtype"] = "default",  
                ["color"] = "0,0,0",   
                ["size"] = 15,           
                ["align"] = "",           
                ["valign"] = "top",   
                ["width"] = 500,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "文件名称需要填写【完整文件名】以及【扩展类型】，例如：test.txt",        
                ["size"] = 12, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "220,20,60",           
                ["width"] = -1,
                ["nowrap"] = 0,
            },	
            {
                ["type"] = "Label", 
                ["text"] = "\n 不填文件名称 【默认随机】\n\n\n\n\n",        
                ["size"] = 15, 
                ["align"] = "left",          
                ["valign"] = "center", 
                ["color"] = "255,140,0",           
                ["width"] = -1,
                ["nowrap"] = 1,--下个控件不换行
            },	
			
        },

        {			
            {
                ["type"] = "Label", 
                ["text"] = "⚠️",        
                ["size"] = 70, 
                ["align"] = "center",          
                ["valign"] = "center", 
                ["color"] = "220,20,60",           
                --["width"] = -1,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "禁止使用脚本做违反国家法律法规的行为",        
                ["size"] = 18, 
                ["align"] = "center",          
                ["valign"] = "center", 
                ["color"] = "220,20,60",           
                --["width"] = -1,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "若使用者使用脚本实施违反当地法律法规或道德风俗的行为",        
                ["size"] = 15, 
                ["align"] = "center",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                --["width"] = -1,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "【使用者应当为此独立承担责任】",        
                ["size"] = 15, 
                ["align"] = "center",          
                ["valign"] = "center", 
                ["color"] = "220,20,60",           
                --["width"] = -1,
                ["nowrap"] = 0 ,
            },
            {
                ["type"] = "Label", 
                ["text"] = "脚本不承担任何责任。\n\n\n",        
                ["size"] = 15, 
                ["align"] = "center",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                --["width"] = -1,
                ["nowrap"] = 0,
            },
            {
                ["type"] = "Label", 
                ["text"] = "软件仅供学习与交流，请于24小时内删除本软件！！！",        
                ["size"] = 12, 
                ["align"] = "center",          
                ["valign"] = "center", 
                ["color"] = "0,0,0",           
                --["width"] = -1,
                ["nowrap"] = 0,
				
            }			
        },
    }   
}
local MyJsonString = cjson.encode(MyTable);
UIret,values = showUI(MyJsonString)